Updated loading functions. Added updated correction script for phospho data, as well as the nmf scripts (in progress)
PNNL-CompBio/BeatAMLproteomics pull request #22
Opened 2021-11-23 19:52 UTC by CamiloPosso

2021-11-30 23:18 UTC, sgosline requested changes
Please address the data issues and the file path/naming issues.

2021-11-30 23:18 UTC, sgosline commented on Pilot Manuscript scripts/NMF Clustering/NMF cophenetic.Rmd
> +title: "PTRC Ex10 Batch correction and normalization"
this is not hte correct title or author

2021-11-30 23:18 UTC, sgosline commented on Pilot Manuscript scripts/NMF Clustering/NMF cophenetic.Rmd
> +source("NMF helper.R")
Can you change the name of this directory to 'analysis/NMF' it is best to avoid spaces in paths and also it's not the pilot manuscript...

2021-11-30 23:18 UTC, sgosline commented on Pilot Manuscript scripts/NMF Clustering/NMF cophenetic.Rmd
> +load("../../Misc/loaded data.RData")
please leave data out of the repo

2021-11-30 23:18 UTC, sgosline commented on Pilot Manuscript scripts/NMF Clustering/NMF helper.R
> +
again see the comment about spaces in file paths

2021-11-30 23:18 UTC, sgosline commented on Pilot Manuscript scripts/NMF Clustering/NMF raw results.Rmd
> +load("../../Misc/loaded data.RData")
remove the loaded data. we can't have patient data on an open github repository

2021-12-01 21:14 UTC, CamiloPosso commented
Updated the files to account for the feedback

2021-12-02 02:59 UTC, merged